config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'tasks#index'
  # Defines the root path route ("/")
  # root "posts#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'task_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find, only: %i[show edit update destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params_task)
    @task.save!
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(params_task)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_find
    @task = Task.find(params[:id])
  end

  def params_task
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Your Task</h1>
<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.check_box :completed %>
  <%= form.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="text-center">My Tasks</h1>

<%= link_to 'Create a new task', tasks_new_path, class: "btn btn-primary m-4" %>
</div>
<% @tasks.each do |task| %>
<div class="cards">
<div class="card m-2" style="max-width: 18rem;">
  <div class="card-body text-center ">
    <h5 class="card-title"><%= link_to "#{task.title}", task_path(task) %></h5>
    <div class="d-flex justify-content-center align-item-center">
    <p class="card-text"><%= "#{task.details}"%></p>
    <input type="checkbox" <%= 'checked' if task.completed == true %> class="m-2">
    </div>
    <div>
    <%= link_to 'Edit task', task_edit_path(task), class: "btn btn-warning" %>
    <%= link_to "Delete",
  task_path(task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger"
%>
<% end %>
</div>
</div>
</div>
</div>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<input type="checkbox" <%= 'checked' if @task.completed == true %>>
<%= link_to 'Back to list', tasks_path %>